### ISSUE TITLE
lua-resty-jwt - new version

### ISSUE THREAD

**Issue by bsiara** [codiy1992/lua-resty-waf#1]
Due to project dependencies I suggest use https://opm.openresty.org/package/cdbattags/lua-resty-jwt which is supported.

**Comment by jeffizz** [comment]
Good idea! I have replaced SkyLothar/lua-resty-jwt with cdbattags/lua-resty-jwt and released version [v1.2.4](https://github.com/codiy1992/lua-resty-waf/releases/tag/v1.2.4). Thank you for your suggestion.
